# docker-compose.yml
version: '3'

services:
  novel-downloader:
    container_name: fanqienovel-downloader
    build: .
    ports:
      - "12930:80"  #web访问端口，12390可改，80别动
    volumes:
      - fanqie_downloads:/app/novels  #fanqie_downloads根据实际需求改，你的和我不一样
      - fanqie_data:/app/data  #fanqie_data根据实际需求改，你的和我不一样
    environment:
      - DOWNLOAD_PATH=/app/novels
      - DATA_PATH=/app/data
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
    network_mode: "bridge"  
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
