# docker-compose.yml
version: '3'

services:
  novel-downloader:
    container_name: fanqienovel-downloader  #容器名称
    build: .
    ports:
      - "12930:80"  #web访问端口，12390可改，80别动
    volumes:
      - /vol1/1000/docker/fanqienovel/novels:/app/novels  #/vol1/1000/docker/fanqienovel根据实际需求改，你的和我不一样
      - /vol1/1000/docker/fanqienovel/data:/app/data  ##/vol1/1000/docker/fanqienovel根据实际需求改，你的和我不一样
    environment:
      - DOWNLOAD_PATH=/app/novels
      - DATA_PATH=/app/data
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
